[package]
name = "a"
version = "0.1.0"
edition = "2021"

[features]
default = []
bob = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
